"""This script dynamically generate pages for the documentation site, including the
API reference and the tutorial notebooks.

It is invoked by the mkdocs-gen-files plugin for MkDocs, which is configured in
mkdocs.yml. The API ref pages are generated by mkdocstrings, and the tutorial notebooks
are converted to HTML by mkdocs-jupyter.
"""

from pathlib import Path

import mkdocs_gen_files

root = Path(__file__).resolve().parents[2]
package = "flygym"


def gen_apiref_pages():
    src_root = root / "src"
    src = src_root / package
    for path in sorted(src.rglob("*.py")):
        module_path = path.relative_to(src_root).with_suffix("")
        doc_path = path.relative_to(src).with_suffix(".md")
        full_doc_path = Path("reference", doc_path)

        parts = tuple(module_path.parts)

        if parts[-1] == "__init__":
            parts = parts[:-1]
        elif parts[-1] == "__main__":
            continue

        with mkdocs_gen_files.open(full_doc_path, "w") as fd:
            identifier = ".".join(parts)
            print("::: " + identifier, file=fd)

        mkdocs_gen_files.set_edit_path(full_doc_path, path.relative_to(root))


def gen_tutorial_pages():
    tutorials_dir = root / "tutorials"
    for nb_path in sorted(tutorials_dir.glob("*.ipynb")):
        dest = Path("tutorials") / nb_path.name
        with mkdocs_gen_files.open(dest, "w") as f:
            f.write(nb_path.read_text(encoding="utf-8"))


# Do not wrap the following in an `if __name__ == "__main__":` guard!
# MkDocs exec()'s this file with __name__ set to the script's path.
gen_apiref_pages()
gen_tutorial_pages()
