name: Check poetry install macOS Intel

on: [push]

env:
  SKIP_RENDERING: "true"

permissions:
  contents: read

jobs:
  build:
    runs-on: macos-13

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      
      - name: Assert poetry.lock exists
        run: |
          if [ ! -f poetry.lock ]; then
            echo "Error: poetry.lock not found!"
            exit 1
          fi

      - name: Install pipx and poetry
        run: |
          python -m pip install --upgrade pip
          pip install pipx
          pipx install poetry

      - name: Install dependencies with poetry
        run: |
          poetry install --extras=dev
      
      - name: Run tests
        run: |
          echo "Tests skipped on macOS Apple Silicon; see issue #233"