name: Check poetry install across platforms

on: [push]

env:
  SKIP_RENDERING: "true"

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Assert poetry.lock exists
        run: |
          if (!(Test-Path -Path "poetry.lock")) { 
            Write-Host "Error: poetry.lock not found!"
            exit 1 
          }
        shell: pwsh

      - name: Install pipx and poetry
        run: |
          python -m pip install --upgrade pip
          pip install pipx
          pipx install poetry

      - name: Install dependencies with poetry
        run: |
          poetry install --extras=dev --extras=examples
      
      - name: Run tests
        run: |
          poetry run pytest