name: Check poetry install macOS Intel

on: [push]

env:
  SKIP_RENDERING: "true"

jobs:
  build:
    runs-on: macos-13

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      
      - name: Assert poetry.lock exists
        run: |
          if [ ! -f poetry.lock ]; then
            echo "Error: poetry.lock not found!"
            exit 1
          fi

      - name: Install pipx and poetry
        run: |
          python -m pip install --upgrade pip
          pip install pipx
          pipx install poetry

      - name: Install dependencies with poetry
        run: |
          poetry install --extras=dev
      
      - name: Run tests
        run: |
          echo "Only running basic tests (not examples) because the latest PyTorch versions "
          echo "don't support Macs with Intel chips. NOTE: Don't do this by simply "
          echo "specifying the test directory with `pytest flygym/tests` because pytest "
          echo "imports everything BEFORE checking which ones to run. See "
          echo "https://stackoverflow.com/a/61677904/13560623"
          cd flygym/tests
          poetry run pytest
